package com.ssa.cms.model;
// Generated May 17, 2013 5:48:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CampaignEmailResponse generated by hbm2java
 */
@Entity
@Table(name="CampaignEmailResponse")
public class CampaignEmailResponse  implements java.io.Serializable {


     private long emailReqNo;
     private String emailStatus;
     private Date effectiveDate;
     private Date endDate;

    public CampaignEmailResponse() {
    }

	
    public CampaignEmailResponse(long emailReqNo, String emailStatus, Date effectiveDate) {
        this.emailReqNo = emailReqNo;
        this.emailStatus = emailStatus;
        this.effectiveDate = effectiveDate;
    }
    public CampaignEmailResponse(long emailReqNo, String emailStatus, Date effectiveDate, Date endDate) {
       this.emailReqNo = emailReqNo;
       this.emailStatus = emailStatus;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
    }
   
     @Id 
    
    @Column(name="Email_Req_No", unique=true, nullable=false)
    public long getEmailReqNo() {
        return this.emailReqNo;
    }
    
    public void setEmailReqNo(long emailReqNo) {
        this.emailReqNo = emailReqNo;
    }
    
    @Column(name="Email_Status", nullable=false, length=8)
    public String getEmailStatus() {
        return this.emailStatus;
    }
    
    public void setEmailStatus(String emailStatus) {
        this.emailStatus = emailStatus;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    

}


