package com.ssa.cms.model;
// Generated Jul 8, 2013 5:57:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IvrcallTiming generated by hbm2java
 */
@Entity
@Table(name="IVRCallTiming")
public class IvrcallTiming  implements java.io.Serializable {


     private int id;
     private int startHour;
     private int startMinute;
     private int endHour;
     private int endMinute;
     private Date effectiveDate;
     private Date endDate;

    public IvrcallTiming() {
    }

	
    public IvrcallTiming(int id, int startHour, int startMinute, int endHour, int endMinute, Date effectiveDate) {
        this.id = id;
        this.startHour = startHour;
        this.startMinute = startMinute;
        this.endHour = endHour;
        this.endMinute = endMinute;
        this.effectiveDate = effectiveDate;
    }
    public IvrcallTiming(int id, int startHour, int startMinute, int endHour, int endMinute, Date effectiveDate, Date endDate) {
       this.id = id;
       this.startHour = startHour;
       this.startMinute = startMinute;
       this.endHour = endHour;
       this.endMinute = endMinute;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Start_Hour", nullable=false)
    public int getStartHour() {
        return this.startHour;
    }
    
    public void setStartHour(int startHour) {
        this.startHour = startHour;
    }
    
    @Column(name="Start_Minute", nullable=false)
    public int getStartMinute() {
        return this.startMinute;
    }
    
    public void setStartMinute(int startMinute) {
        this.startMinute = startMinute;
    }
    
    @Column(name="End_Hour", nullable=false)
    public int getEndHour() {
        return this.endHour;
    }
    
    public void setEndHour(int endHour) {
        this.endHour = endHour;
    }
    
    @Column(name="End_Minute", nullable=false)
    public int getEndMinute() {
        return this.endMinute;
    }
    
    public void setEndMinute(int endMinute) {
        this.endMinute = endMinute;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


