package com.ssa.cms.model;
// Generated May 17, 2013 5:48:00 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailRequest generated by hbm2java
 */
@Entity
@Table(name = "EmailRequest")
public class EmailRequest implements java.io.Serializable {

    private Integer emailReqNo;
    private int campaignId;
    private String messageContext;
    private String email;
    private String emailSubject;
    private byte[] emailBody;
    private String messageTypeCode;
    private int folderId;
    private int messageTypeId;
    private String fileTypeCode;
    private String rxGroupNumber;
    private Date cardholderDob;
    private String fileName;
    private Date fillDate;
    private String ndcNumber;
    private Integer claimStatus;
    private Date effectiveDate;
    private Date endDate;
    private Integer redemptionId;
    private int smtpId;
    private long intervalId;
    private String intervalDescription;
    private String eventDetail;

    public EmailRequest() {
    }

    public EmailRequest(int campaignId, int folderId, int messageTypeId, int smtpId, String fileTypeCode, Date fillDate, Date effectiveDate) {
        this.campaignId = campaignId;
        this.folderId = folderId;
        this.messageTypeId = messageTypeId;
        this.fileTypeCode = fileTypeCode;
        this.fillDate = fillDate;
        this.effectiveDate = effectiveDate;
        this.smtpId = smtpId;
    }

    public EmailRequest(int campaignId, String messageContext, String email, String emailSubject, byte[] emailBody, String messageTypeCode, int folderId, int messageTypeId, String fileTypeCode, String rxGroupNumber, Date cardholderDob, String fileName, Date fillDate, String ndcNumber, Integer claimStatus, Date effectiveDate, Date endDate, Integer redemptionId, int smtpId, long intervalId, String intervalDescription, String eventDetail) {
        this.campaignId = campaignId;
        this.messageContext = messageContext;
        this.email = email;
        this.emailSubject = emailSubject;
        this.emailBody = emailBody;
        this.messageTypeCode = messageTypeCode;
        this.folderId = folderId;
        this.messageTypeId = messageTypeId;
        this.fileTypeCode = fileTypeCode;
        this.rxGroupNumber = rxGroupNumber;
        this.cardholderDob = cardholderDob;
        this.fileName = fileName;
        this.fillDate = fillDate;
        this.ndcNumber = ndcNumber;
        this.claimStatus = claimStatus;
        this.effectiveDate = effectiveDate;
        this.endDate = endDate;
        this.redemptionId = redemptionId;
        this.smtpId = smtpId;
        this.intervalId = intervalId;
        this.intervalDescription = intervalDescription;
        this.eventDetail = eventDetail;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Email_Req_No", unique = true, nullable = false)
    public Integer getEmailReqNo() {
        return this.emailReqNo;
    }

    public void setEmailReqNo(Integer emailReqNo) {
        this.emailReqNo = emailReqNo;
    }

    @Column(name = "Campaign_Id", nullable = false)
    public int getCampaignId() {
        return this.campaignId;
    }

    public void setCampaignId(int campaignId) {
        this.campaignId = campaignId;
    }

    @Column(name = "Message_Context", length = 20)
    public String getMessageContext() {
        return this.messageContext;
    }

    public void setMessageContext(String messageContext) {
        this.messageContext = messageContext;
    }

    @Column(name = "Smtp_Id", nullable = false)
    public int getSmtpId() {
        return this.smtpId;
    }

    public void setSmtpId(int smtpId) {
        this.smtpId = smtpId;
    }

    @Column(name = "Email", length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Email_Subject", length = 200)
    public String getEmailSubject() {
        return this.emailSubject;
    }

    public void setEmailSubject(String emailSubject) {
        this.emailSubject = emailSubject;
    }

    @Column(name = "Email_Body", length = 65535)
    public byte[] getEmailBody() {
        return this.emailBody;
    }

    public void setEmailBody(byte[] emailBody) {
        this.emailBody = emailBody;
    }

    @Column(name = "Message_Type_Code", length = 100)
    public String getMessageTypeCode() {
        return this.messageTypeCode;
    }

    public void setMessageTypeCode(String messageTypeCode) {
        this.messageTypeCode = messageTypeCode;
    }

    @Column(name = "FolderId", nullable = false)
    public int getFolderId() {
        return this.folderId;
    }

    public void setFolderId(int folderId) {
        this.folderId = folderId;
    }

    @Column(name = "MessageTypeId", nullable = false)
    public int getMessageTypeId() {
        return this.messageTypeId;
    }

    public void setMessageTypeId(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }

    @Column(name = "File_Type_Code", nullable = false, length = 6)
    public String getFileTypeCode() {
        return this.fileTypeCode;
    }

    public void setFileTypeCode(String fileTypeCode) {
        this.fileTypeCode = fileTypeCode;
    }

    @Column(name = "Rx_Group_Number", length = 18)
    public String getRxGroupNumber() {
        return this.rxGroupNumber;
    }

    public void setRxGroupNumber(String rxGroupNumber) {
        this.rxGroupNumber = rxGroupNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "Cardholder_DOB", length = 10)
    public Date getCardholderDob() {
        return this.cardholderDob;
    }

    public void setCardholderDob(Date cardholderDob) {
        this.cardholderDob = cardholderDob;
    }

    @Column(name = "File_Name", length = 125)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "Fill_Date", nullable = false, length = 10)
    public Date getFillDate() {
        return this.fillDate;
    }

    public void setFillDate(Date fillDate) {
        this.fillDate = fillDate;
    }

    @Column(name = "NDC_Number", length = 12)
    public String getNdcNumber() {
        return this.ndcNumber;
    }

    public void setNdcNumber(String ndcNumber) {
        this.ndcNumber = ndcNumber;
    }

    @Column(name = "Claim_Status")
    public Integer getClaimStatus() {
        return this.claimStatus;
    }

    public void setClaimStatus(Integer claimStatus) {
        this.claimStatus = claimStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Effective_Date", nullable = false, length = 19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "End_Date", length = 19)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Column(name = "Redemption_Id")
    public Integer getRedemptionId() {
        return this.redemptionId;
    }

    public void setRedemptionId(Integer redemptionId) {
        this.redemptionId = redemptionId;
    }

    @Column(name = "Interval_Id")
    public long getIntervalId() {
        return intervalId;
    }

    public void setIntervalId(long intervalId) {
        this.intervalId = intervalId;
    }

    @Column(name = "Interval_Description", length = 50)
    public String getIntervalDescription() {
        return intervalDescription;
    }

    public void setIntervalDescription(String intervalDescription) {
        this.intervalDescription = intervalDescription;
    }

    @Column(name = "Event_Detail", length = 255)
    public String getEventDetail() {
        return eventDetail;
    }

    public void setEventDetail(String eventDetail) {
        this.eventDetail = eventDetail;
    }
}
