package com.ssa.cms.model;
// Generated May 17, 2013 5:48:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailCouponOffered generated by hbm2java
 */
@Entity
@Table(name="EmailCouponOffered")
public class EmailCouponOffered  implements java.io.Serializable {


     private long ecrSeqNo;
     private Integer campaignId;
     private String campaignName;
     private String email;
     private String keywordCode;
     private Date effectiveDate;
     private Date endDate;
     private String cardNumber;

    public EmailCouponOffered() {
    }

	
    public EmailCouponOffered(long ecrSeqNo, Date effectiveDate) {
        this.ecrSeqNo = ecrSeqNo;
        this.effectiveDate = effectiveDate;
    }
    public EmailCouponOffered(long ecrSeqNo, Integer campaignId, String campaignName, String email, String keywordCode, Date effectiveDate, Date endDate, String cardNumber) {
       this.ecrSeqNo = ecrSeqNo;
       this.campaignId = campaignId;
       this.campaignName = campaignName;
       this.email = email;
       this.keywordCode = keywordCode;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
       this.cardNumber = cardNumber;
    }
   
     @Id 
    
    @Column(name="ECR_Seq_No", unique=true, nullable=false)
    public long getEcrSeqNo() {
        return this.ecrSeqNo;
    }
    
    public void setEcrSeqNo(long ecrSeqNo) {
        this.ecrSeqNo = ecrSeqNo;
    }
    
    @Column(name="Campaign_Id")
    public Integer getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }
    
    @Column(name="Campaign_Name")
    public String getCampaignName() {
        return this.campaignName;
    }
    
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }
    
    @Column(name="Email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="Keyword_Code", length=10)
    public String getKeywordCode() {
        return this.keywordCode;
    }
    
    public void setKeywordCode(String keywordCode) {
        this.keywordCode = keywordCode;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="Card_Number", length=20)
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }




}


