package com.ssa.cms.model;
// Generated Apr 30, 2013 5:37:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AggregatorMessageResponse generated by hbm2java
 * 
 * Table not exist in Db
 */
//@Entity
//@Table(name="AggregatorMessageResponse")
public class AggregatorMessageResponse  implements java.io.Serializable {


     private long messageReqNo;
     private String errorCode;
     private String errorDescription;
     private String ticketId;
     private String messageResponse;
     private Date effectiveDate;
     private Date endDate;
     private String mtsId;

    public AggregatorMessageResponse() {
    }

	
    public AggregatorMessageResponse(long messageReqNo, String errorCode, String errorDescription, String ticketId, String messageResponse, Date effectiveDate) {
        this.messageReqNo = messageReqNo;
        this.errorCode = errorCode;
        this.errorDescription = errorDescription;
        this.ticketId = ticketId;
        this.messageResponse = messageResponse;
        this.effectiveDate = effectiveDate;
    }
    public AggregatorMessageResponse(long messageReqNo, String errorCode, String errorDescription, String ticketId, String messageResponse, Date effectiveDate, Date endDate, String mtsId) {
       this.messageReqNo = messageReqNo;
       this.errorCode = errorCode;
       this.errorDescription = errorDescription;
       this.ticketId = ticketId;
       this.messageResponse = messageResponse;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
       this.mtsId = mtsId;
    }
   
//     @Id 
//    
//    @Column(name="Message_Req_No", unique=true, nullable=false)
    public long getMessageReqNo() {
        return this.messageReqNo;
    }
    
    public void setMessageReqNo(long messageReqNo) {
        this.messageReqNo = messageReqNo;
    }
    
//    @Column(name="Error_Code", nullable=false, length=5)
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
    
//    @Column(name="Error_Description", nullable=false, length=200)
    public String getErrorDescription() {
        return this.errorDescription;
    }
    
    public void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }
    
//    @Column(name="Ticket_ID", length=50)
    public String getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }
    
//    @Column(name="Message_Response", nullable=false, length=10000)
    public String getMessageResponse() {
        return this.messageResponse;
    }
    
    public void setMessageResponse(String messageResponse) {
        this.messageResponse = messageResponse;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
//    @Column(name="MTS_ID", length=20)
    public String getMtsId() {
        return this.mtsId;
    }
    
    public void setMtsId(String mtsId) {
        this.mtsId = mtsId;
    }




}


