package com.ssa.cms.model;
// Generated May 17, 2013 5:48:00 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CampaignEmailRequest generated by hbm2java
 */
@Entity
@Table(name = "CampaignEmailRequest")
public class CampaignEmailRequest implements java.io.Serializable {

    private Integer emailReqNo;
    private Integer ecrSeqNo;
    private Integer smtpId;
    private String campaignName;
    private Integer campaignId;
    private String email;
    private String emailSubject;
    private byte[] emailBody;
    private String messageTypeCode;
    private Integer folderId;
    private Integer messageTypeId;
    private Integer messageId;
    private String cmsEvent;
    private String cmsInterval;
    private String reminderCategoryCode;
    private Date effectiveDate;
    private Date endDate;
    private long intervalId;
    private String intervalDescription;
    private String eventDetail;

    public CampaignEmailRequest() {
    }

    public CampaignEmailRequest(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public CampaignEmailRequest(Integer ecrSeqNo, Integer smtpId, String campaignName, Integer campaignId, String email, String emailSubject, byte[] emailBody, String messageTypeCode, Integer folderId, Integer messageTypeId, Integer messageId, String cmsEvent, String cmsInterval, String reminderCategoryCode, Date effectiveDate, Date endDate, long intervalId, String intervalDescription, String eventDetail) {
        this.ecrSeqNo = ecrSeqNo;
        this.smtpId = smtpId;
        this.campaignName = campaignName;
        this.campaignId = campaignId;
        this.email = email;
        this.emailSubject = emailSubject;
        this.emailBody = emailBody;
        this.messageTypeCode = messageTypeCode;
        this.folderId = folderId;
        this.messageTypeId = messageTypeId;
        this.messageId = messageId;
        this.cmsEvent = cmsEvent;
        this.cmsInterval = cmsInterval;
        this.reminderCategoryCode = reminderCategoryCode;
        this.effectiveDate = effectiveDate;
        this.endDate = endDate;
        this.intervalId = intervalId;
        this.intervalDescription = intervalDescription;
        this.eventDetail = eventDetail;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Email_Req_No", unique = true, nullable = false)
    public Integer getEmailReqNo() {
        return this.emailReqNo;
    }

    public void setEmailReqNo(Integer emailReqNo) {
        this.emailReqNo = emailReqNo;
    }

    @Column(name = "ECR_Seq_No")
    public Integer getEcrSeqNo() {
        return this.ecrSeqNo;
    }

    public void setEcrSeqNo(Integer ecrSeqNo) {
        this.ecrSeqNo = ecrSeqNo;
    }

    @Column(name = "SmtpId")
    public Integer getSmtpId() {
        return this.smtpId;
    }

    public void setSmtpId(Integer smtpId) {
        this.smtpId = smtpId;
    }

    @Column(name = "Campaign_Name")
    public String getCampaignName() {
        return this.campaignName;
    }

    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    @Column(name = "Campaign_Id")
    public Integer getCampaignId() {
        return this.campaignId;
    }

    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    @Column(name = "Email", length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Email_Subject", length = 200)
    public String getEmailSubject() {
        return this.emailSubject;
    }

    public void setEmailSubject(String emailSubject) {
        this.emailSubject = emailSubject;
    }

    @Column(name = "Email_Body", length = 65535)
    public byte[] getEmailBody() {
        return this.emailBody;
    }

    public void setEmailBody(byte[] emailBody) {
        this.emailBody = emailBody;
    }

    @Column(name = "Message_Type_Code", length = 100)
    public String getMessageTypeCode() {
        return this.messageTypeCode;
    }

    public void setMessageTypeCode(String messageTypeCode) {
        this.messageTypeCode = messageTypeCode;
    }

    @Column(name = "Folder_Id")
    public Integer getFolderId() {
        return this.folderId;
    }

    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    @Column(name = "Message_Type_Id")
    public Integer getMessageTypeId() {
        return this.messageTypeId;
    }

    public void setMessageTypeId(Integer messageTypeId) {
        this.messageTypeId = messageTypeId;
    }

    @Column(name = "Message_Id")
    public Integer getMessageId() {
        return this.messageId;
    }

    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    @Column(name = "CMS_Event", length = 50)
    public String getCmsEvent() {
        return this.cmsEvent;
    }

    public void setCmsEvent(String cmsEvent) {
        this.cmsEvent = cmsEvent;
    }

    @Column(name = "CMS_Interval", length = 10)
    public String getCmsInterval() {
        return this.cmsInterval;
    }

    public void setCmsInterval(String cmsInterval) {
        this.cmsInterval = cmsInterval;
    }

    @Column(name = "Reminder_Category_Code", length = 10)
    public String getReminderCategoryCode() {
        return this.reminderCategoryCode;
    }

    public void setReminderCategoryCode(String reminderCategoryCode) {
        this.reminderCategoryCode = reminderCategoryCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Effective_Date", nullable = false, length = 19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "End_Date", length = 19)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Column(name = "Interval_Id")
    public long getIntervalId() {
        return intervalId;
    }

    public void setIntervalId(long intervalId) {
        this.intervalId = intervalId;
    }

    @Column(name = "Interval_Description", length = 50)
    public String getIntervalDescription() {
        return intervalDescription;
    }

    public void setIntervalDescription(String intervalDescription) {
        this.intervalDescription = intervalDescription;
    }

    @Column(name = "Event_Detail", length = 255)
    public String getEventDetail() {
        return eventDetail;
    }

    public void setEventDetail(String eventDetail) {
        this.eventDetail = eventDetail;
    }
}
