package com.ssa.cms.model;
// Generated Mar 27, 2013 2:07:39 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Drfprocessed generated by hbm2java
 * 
 * DRFProcessed table not exist
 */
//@Entity
//@Table(name="DRFProcessed")
public class Drfprocessed  implements java.io.Serializable {


     private DrfprocessedId id;
     private String submittedId;
     private Date cardholderDob;
     private String programCode;
     private Integer redemptionChannelId;
     private String redemptionChannelTitle;
     private String ndcNumber;
     private Date fillDate;
     private int campaignId;
     private String rxGroupNumber;
     private long redemptionCount;
     private Date postingDate;
     private String cardholderFirstName;
     private String cardholderLastName;
     private String memberId;
     private String prescriptionNumber;
     private String claimSource;
     private Date reversalDate;
     private String productName;
     private Integer gpi;
     private Long fdbGcn;
     private String fileTypeCode;
     private String therapeuticClassDesc;
     private Double quantity;
     private Integer daysSupply;
     private String cardholderId;
     private Character cardholderGender;
     private Integer refillsUsed;
     private String pharmacyNpi;
     private String pharmacyName;
     private String pharmacyCity;
     private String pharmacyState;
     private String pharmacyZipCode;
     private String pharmacyPhone;
     private String deaNumber;
     private String prescriberNpi;
     private String prescriberFirstName;
     private String prescriberLastName;
     private String prescriberAddress1;
     private String prescriberAddress2;
     private String prescriberCity;
     private String prescriberState;
     private String prescriberZipCode;
     private BigDecimal totDrugCostPaidToPharmacy;
     private BigDecimal ptOutOfPocket;
     private Integer ciPaperClaimFlag;
     private Integer ciOtherProcessorFlag;
     private Integer ciBatchProcessedFlag;
     private Integer ciTestClaimFlag;
     private Integer ciDirectReimbursementFlag;
     private Double professionalServiceFee;
     private String drugDosageForm;
     private String drugStrength;
     private Integer refillsAllowed;
     private BigDecimal ingredientCostPaid;
     private double flatSalesTaxAmountPaid;
     private BigDecimal usualCustomaryAmount;
     private Long priorAuthCode;
     private String pharmacyAddress1;
     private String pharmacyAddress2;
     private double dispenseFeePaid;
     private String prescriberSpecialty;
     private String priceSource;
     private String reversalDateTimeStamp;
     private Date rxWrittenDate;
     private Long pharmacyNcpdp;
     private String submittedCardholderFirstName;
     private String submittedCardholderLastName;
     private Date submittedCardholderDob;
     private String submittedCardholderGender;
     private String submittedPatientFname;
     private String submittedPatientLname;
     private String fileName;
     private Date effectiveDate;
     private Date insertionDate;
     private Integer enrollmentId;
     private String communicationSourceCode;
     private String communicationMethod;
     private String communicationId;
     private Date enrollmentDate;
     private String isValidPhone;
     private String claimAuthorizationNumber;
     private String orignalClaimAuthorizationNumber;
     private String otherCoverageCode;
     private String otherPayerRejectionCode;
     private String otherPayerIdQualifier;
     private String otherPayerId;
     private Long inputReferenceNumber;
     private String enrollmentPath;
     private Integer redemptionId;
     private Date postingDateTimeStamp;

    public Drfprocessed() {
    }

	
    public Drfprocessed(DrfprocessedId id, String ndcNumber, Date fillDate, int campaignId, long redemptionCount, Date postingDate, String claimSource, BigDecimal totDrugCostPaidToPharmacy, BigDecimal ingredientCostPaid, double flatSalesTaxAmountPaid, BigDecimal usualCustomaryAmount, double dispenseFeePaid, String priceSource, String fileName, Date effectiveDate) {
        this.id = id;
        this.ndcNumber = ndcNumber;
        this.fillDate = fillDate;
        this.campaignId = campaignId;
        this.redemptionCount = redemptionCount;
        this.postingDate = postingDate;
        this.claimSource = claimSource;
        this.totDrugCostPaidToPharmacy = totDrugCostPaidToPharmacy;
        this.ingredientCostPaid = ingredientCostPaid;
        this.flatSalesTaxAmountPaid = flatSalesTaxAmountPaid;
        this.usualCustomaryAmount = usualCustomaryAmount;
        this.dispenseFeePaid = dispenseFeePaid;
        this.priceSource = priceSource;
        this.fileName = fileName;
        this.effectiveDate = effectiveDate;
    }
    public Drfprocessed(Date postingDateTimeStamp,DrfprocessedId id, String submittedId, Date cardholderDob, String programCode, Integer redemptionChannelId, String redemptionChannelTitle, String ndcNumber, Date fillDate, int campaignId, String rxGroupNumber, long redemptionCount, Date postingDate, String cardholderFirstName, String cardholderLastName, String memberId, String prescriptionNumber, String claimSource, Date reversalDate, String productName, Integer gpi, Long fdbGcn, String fileTypeCode, String therapeuticClassDesc, Double quantity, Integer daysSupply, String cardholderId, Character cardholderGender, Integer refillsUsed, String pharmacyNpi, String pharmacyName, String pharmacyCity, String pharmacyState, String pharmacyZipCode, String pharmacyPhone, String deaNumber, String prescriberNpi, String prescriberFirstName, String prescriberLastName, String prescriberAddress1, String prescriberAddress2, String prescriberCity, String prescriberState, String prescriberZipCode, BigDecimal totDrugCostPaidToPharmacy,  BigDecimal ptOutOfPocket, Integer ciPaperClaimFlag, Integer ciOtherProcessorFlag, Integer ciBatchProcessedFlag, Integer ciTestClaimFlag, Integer ciDirectReimbursementFlag, Double professionalServiceFee, String drugDosageForm, String drugStrength, Integer refillsAllowed, BigDecimal ingredientCostPaid, double flatSalesTaxAmountPaid, BigDecimal usualCustomaryAmount, Long priorAuthCode, String pharmacyAddress1, String pharmacyAddress2, double dispenseFeePaid, String prescriberSpecialty, String priceSource, String reversalDateTimeStamp, Date rxWrittenDate, Long pharmacyNcpdp, String submittedCardholderFirstName, String submittedCardholderLastName, Date submittedCardholderDob, String submittedCardholderGender, String submittedPatientFname, String submittedPatientLname, String fileName, Date effectiveDate, Date insertionDate, Integer enrollmentId, String communicationSourceCode, String communicationMethod, String communicationId, Date enrollmentDate, String isValidPhone, String claimAuthorizationNumber, String orignalClaimAuthorizationNumber, String otherCoverageCode, String otherPayerRejectionCode, String otherPayerIdQualifier, String otherPayerId, Long inputReferenceNumber, String enrollmentPath, Integer redemptionId) {
       this.id = id;
       this.submittedId = submittedId;
       this.cardholderDob = cardholderDob;
       this.programCode = programCode;
       this.redemptionChannelId = redemptionChannelId;
       this.redemptionChannelTitle = redemptionChannelTitle;
       this.ndcNumber = ndcNumber;
       this.fillDate = fillDate;
       this.campaignId = campaignId;
       this.rxGroupNumber = rxGroupNumber;
       this.redemptionCount = redemptionCount;
       this.postingDate = postingDate;
       this.cardholderFirstName = cardholderFirstName;
       this.cardholderLastName = cardholderLastName;
       this.memberId = memberId;
       this.prescriptionNumber = prescriptionNumber;
       this.claimSource = claimSource;
       this.reversalDate = reversalDate;
       this.productName = productName;
       this.gpi = gpi;
       this.fdbGcn = fdbGcn;
       this.fileTypeCode = fileTypeCode;
       this.therapeuticClassDesc = therapeuticClassDesc;
       this.quantity = quantity;
       this.daysSupply = daysSupply;
       this.cardholderId = cardholderId;
       this.cardholderGender = cardholderGender;
       this.refillsUsed = refillsUsed;
       this.pharmacyNpi = pharmacyNpi;
       this.pharmacyName = pharmacyName;
       this.pharmacyCity = pharmacyCity;
       this.pharmacyState = pharmacyState;
       this.pharmacyZipCode = pharmacyZipCode;
       this.pharmacyPhone = pharmacyPhone;
       this.deaNumber = deaNumber;
       this.prescriberNpi = prescriberNpi;
       this.prescriberFirstName = prescriberFirstName;
       this.prescriberLastName = prescriberLastName;
       this.prescriberAddress1 = prescriberAddress1;
       this.prescriberAddress2 = prescriberAddress2;
       this.prescriberCity = prescriberCity;
       this.prescriberState = prescriberState;
       this.prescriberZipCode = prescriberZipCode;
       this.totDrugCostPaidToPharmacy = totDrugCostPaidToPharmacy;
       this.ptOutOfPocket = ptOutOfPocket;
       this.ciPaperClaimFlag = ciPaperClaimFlag;
       this.ciOtherProcessorFlag = ciOtherProcessorFlag;
       this.ciBatchProcessedFlag = ciBatchProcessedFlag;
       this.ciTestClaimFlag = ciTestClaimFlag;
       this.ciDirectReimbursementFlag = ciDirectReimbursementFlag;
       this.professionalServiceFee = professionalServiceFee;
       this.drugDosageForm = drugDosageForm;
       this.drugStrength = drugStrength;
       this.refillsAllowed = refillsAllowed;
       this.ingredientCostPaid = ingredientCostPaid;
       this.flatSalesTaxAmountPaid = flatSalesTaxAmountPaid;
       this.usualCustomaryAmount = usualCustomaryAmount;
       this.priorAuthCode = priorAuthCode;
       this.pharmacyAddress1 = pharmacyAddress1;
       this.pharmacyAddress2 = pharmacyAddress2;
       this.dispenseFeePaid = dispenseFeePaid;
       this.prescriberSpecialty = prescriberSpecialty;
       this.priceSource = priceSource;
       this.reversalDateTimeStamp = reversalDateTimeStamp;
       this.rxWrittenDate = rxWrittenDate;
       this.pharmacyNcpdp = pharmacyNcpdp;
       this.submittedCardholderFirstName = submittedCardholderFirstName;
       this.submittedCardholderLastName = submittedCardholderLastName;
       this.submittedCardholderDob = submittedCardholderDob;
       this.submittedCardholderGender = submittedCardholderGender;
       this.submittedPatientFname = submittedPatientFname;
       this.submittedPatientLname = submittedPatientLname;
       this.fileName = fileName;
       this.effectiveDate = effectiveDate;
       this.insertionDate = insertionDate;
       this.enrollmentId = enrollmentId;
       this.communicationSourceCode = communicationSourceCode;
       this.communicationMethod = communicationMethod;
       this.communicationId = communicationId;
       this.enrollmentDate = enrollmentDate;
       this.isValidPhone = isValidPhone;
       this.claimAuthorizationNumber = claimAuthorizationNumber;
       this.orignalClaimAuthorizationNumber = orignalClaimAuthorizationNumber;
       this.otherCoverageCode = otherCoverageCode;
       this.otherPayerRejectionCode = otherPayerRejectionCode;
       this.otherPayerIdQualifier = otherPayerIdQualifier;
       this.otherPayerId = otherPayerId;
       this.inputReferenceNumber = inputReferenceNumber;
       this.enrollmentPath = enrollmentPath;
       this.redemptionId = redemptionId;
       this.postingDateTimeStamp = postingDateTimeStamp;
    }
   
//     @EmbeddedId
//    
//    @AttributeOverrides( {
//        @AttributeOverride(name="claimStatus", column=@Column(name="Claim_Status", nullable=false) ), 
//        @AttributeOverride(name="transactionNumber", column=@Column(name="Transaction_Number", nullable=false, length=15) ) } )
    public DrfprocessedId getId() {
        return this.id;
    }
    
    public void setId(DrfprocessedId id) {
        this.id = id;
    }
    
  //  @Column(name="Submitted_Id", length=11)
    public String getSubmittedId() {
        return this.submittedId;
    }
    
    public void setSubmittedId(String submittedId) {
        this.submittedId = submittedId;
    }
//    @Temporal(TemporalType.DATE)
//    @Column(name="Cardholder_DOB", length=10)
    public Date getCardholderDob() {
        return this.cardholderDob;
    }
    
    public void setCardholderDob(Date cardholderDob) {
        this.cardholderDob = cardholderDob;
    }
    
//    @Column(name="Program_Code", length=25)
    public String getProgramCode() {
        return this.programCode;
    }
    
    public void setProgramCode(String programCode) {
        this.programCode = programCode;
    }
    
//    @Column(name="Redemption_Channel_Id")
    public Integer getRedemptionChannelId() {
        return this.redemptionChannelId;
    }
    
    public void setRedemptionChannelId(Integer redemptionChannelId) {
        this.redemptionChannelId = redemptionChannelId;
    }
    
//    @Column(name="Redemption_Channel_Title", length=50)
    public String getRedemptionChannelTitle() {
        return this.redemptionChannelTitle;
    }
    
    public void setRedemptionChannelTitle(String redemptionChannelTitle) {
        this.redemptionChannelTitle = redemptionChannelTitle;
    }
    
//    @Column(name="NDC_Number", nullable=false, length=12)
    public String getNdcNumber() {
        return this.ndcNumber;
    }
    
    public void setNdcNumber(String ndcNumber) {
        this.ndcNumber = ndcNumber;
    }
//    @Temporal(TemporalType.DATE)
//    @Column(name="Fill_Date", nullable=false, length=10)
    public Date getFillDate() {
        return this.fillDate;
    }
    
    public void setFillDate(Date fillDate) {
        this.fillDate = fillDate;
    }
    
//    @Column(name="CampaignId", nullable=false)
    public int getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(int campaignId) {
        this.campaignId = campaignId;
    }
    
//    @Column(name="Rx_Group_Number", length=15)
    public String getRxGroupNumber() {
        return this.rxGroupNumber;
    }
    
    public void setRxGroupNumber(String rxGroupNumber) {
        this.rxGroupNumber = rxGroupNumber;
    }
    
//    @Column(name="Redemption_Count", nullable=false)
    public long getRedemptionCount() {
        return this.redemptionCount;
    }
    
    public void setRedemptionCount(long redemptionCount) {
        this.redemptionCount = redemptionCount;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Posting_Date", nullable=false, length=19)
    public Date getPostingDate() {
        return this.postingDate;
    }
    
    public void setPostingDate(Date postingDate) {
        this.postingDate = postingDate;
    }
    
//    @Column(name="Cardholder_First_Name", length=30)
    public String getCardholderFirstName() {
        return this.cardholderFirstName;
    }
    
    public void setCardholderFirstName(String cardholderFirstName) {
        this.cardholderFirstName = cardholderFirstName;
    }
    
//    @Column(name="Cardholder_Last_Name", length=30)
    public String getCardholderLastName() {
        return this.cardholderLastName;
    }
    
    public void setCardholderLastName(String cardholderLastName) {
        this.cardholderLastName = cardholderLastName;
    }
    
//    @Column(name="Member_ID", length=50)
    public String getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }
    
//    @Column(name="Prescription_Number", length=12)
    public String getPrescriptionNumber() {
        return this.prescriptionNumber;
    }
    
    public void setPrescriptionNumber(String prescriptionNumber) {
        this.prescriptionNumber = prescriptionNumber;
    }
    
//    @Column(name="Claim_Source", nullable=false, length=20)
    public String getClaimSource() {
        return this.claimSource;
    }
    
    public void setClaimSource(String claimSource) {
        this.claimSource = claimSource;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Reversal_Date", length=19)
    public Date getReversalDate() {
        return this.reversalDate;
    }
    
    public void setReversalDate(Date reversalDate) {
        this.reversalDate = reversalDate;
    }
    
//    @Column(name="Product_Name", length=35)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    
//    @Column(name="GPI")
    public Integer getGpi() {
        return this.gpi;
    }
    
    public void setGpi(Integer gpi) {
        this.gpi = gpi;
    }
    
//    @Column(name="FDB_GCN")
    public Long getFdbGcn() {
        return this.fdbGcn;
    }
    
    public void setFdbGcn(Long fdbGcn) {
        this.fdbGcn = fdbGcn;
    }
    
//    @Column(name="File_Type_Code", length=3)
    public String getFileTypeCode() {
        return this.fileTypeCode;
    }
    
    public void setFileTypeCode(String fileTypeCode) {
        this.fileTypeCode = fileTypeCode;
    }
    
//    @Column(name="Therapeutic_Class_Desc", length=50)
    public String getTherapeuticClassDesc() {
        return this.therapeuticClassDesc;
    }
    
    public void setTherapeuticClassDesc(String therapeuticClassDesc) {
        this.therapeuticClassDesc = therapeuticClassDesc;
    }
    
//    @Column(name="Quantity", precision=22, scale=0)
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    
//    @Column(name="Days_Supply")
    public Integer getDaysSupply() {
        return this.daysSupply;
    }
    
    public void setDaysSupply(Integer daysSupply) {
        this.daysSupply = daysSupply;
    }
    
//    @Column(name="Cardholder_ID", length=20)
    public String getCardholderId() {
        return this.cardholderId;
    }
    
    public void setCardholderId(String cardholderId) {
        this.cardholderId = cardholderId;
    }
    
//    @Column(name="Cardholder_Gender", length=1)
    public Character getCardholderGender() {
        return this.cardholderGender;
    }
    
    public void setCardholderGender(Character cardholderGender) {
        this.cardholderGender = cardholderGender;
    }
    
//    @Column(name="Refills_Used")
    public Integer getRefillsUsed() {
        return this.refillsUsed;
    }
    
    public void setRefillsUsed(Integer refillsUsed) {
        this.refillsUsed = refillsUsed;
    }
    
//    @Column(name="Pharmacy_NPI", length=10)
    public String getPharmacyNpi() {
        return this.pharmacyNpi;
    }
    
    public void setPharmacyNpi(String pharmacyNpi) {
        this.pharmacyNpi = pharmacyNpi;
    }
    
//    @Column(name="Pharmacy_Name", length=200)
    public String getPharmacyName() {
        return this.pharmacyName;
    }
    
    public void setPharmacyName(String pharmacyName) {
        this.pharmacyName = pharmacyName;
    }
    
//    @Column(name="Pharmacy_City", length=18)
    public String getPharmacyCity() {
        return this.pharmacyCity;
    }
    
    public void setPharmacyCity(String pharmacyCity) {
        this.pharmacyCity = pharmacyCity;
    }
    
//    @Column(name="Pharmacy_State", length=2)
    public String getPharmacyState() {
        return this.pharmacyState;
    }
    
    public void setPharmacyState(String pharmacyState) {
        this.pharmacyState = pharmacyState;
    }
    
//    @Column(name="Pharmacy_Zip_Code", length=10)
    public String getPharmacyZipCode() {
        return this.pharmacyZipCode;
    }
    
    public void setPharmacyZipCode(String pharmacyZipCode) {
        this.pharmacyZipCode = pharmacyZipCode;
    }
    
//    @Column(name="Pharmacy_Phone", length=10)
    public String getPharmacyPhone() {
        return this.pharmacyPhone;
    }
    
    public void setPharmacyPhone(String pharmacyPhone) {
        this.pharmacyPhone = pharmacyPhone;
    }
    
//    @Column(name="DEA_Number", length=9)
    public String getDeaNumber() {
        return this.deaNumber;
    }
    
    public void setDeaNumber(String deaNumber) {
        this.deaNumber = deaNumber;
    }
    
    //@Column(name="Prescriber_NPI", length=12)
    public String getPrescriberNpi() {
        return this.prescriberNpi;
    }
    
    public void setPrescriberNpi(String prescriberNpi) {
        this.prescriberNpi = prescriberNpi;
    }
    
//    @Column(name="Prescriber_First_Name", length=50)
    public String getPrescriberFirstName() {
        return this.prescriberFirstName;
    }
    
    public void setPrescriberFirstName(String prescriberFirstName) {
        this.prescriberFirstName = prescriberFirstName;
    }
    
//    @Column(name="Prescriber_Last_Name", length=50)
    public String getPrescriberLastName() {
        return this.prescriberLastName;
    }
    
    public void setPrescriberLastName(String prescriberLastName) {
        this.prescriberLastName = prescriberLastName;
    }
    
//    @Column(name="Prescriber_Address_1", length=40)
    public String getPrescriberAddress1() {
        return this.prescriberAddress1;
    }
    
    public void setPrescriberAddress1(String prescriberAddress1) {
        this.prescriberAddress1 = prescriberAddress1;
    }
    
//    @Column(name="Prescriber_Address_2", length=40)
    public String getPrescriberAddress2() {
        return this.prescriberAddress2;
    }
    
    public void setPrescriberAddress2(String prescriberAddress2) {
        this.prescriberAddress2 = prescriberAddress2;
    }
    
//    @Column(name="Prescriber_City", length=24)
    public String getPrescriberCity() {
        return this.prescriberCity;
    }
    
    public void setPrescriberCity(String prescriberCity) {
        this.prescriberCity = prescriberCity;
    }
    
   // @Column(name="Prescriber_State", length=2)
    public String getPrescriberState() {
        return this.prescriberState;
    }
    
    public void setPrescriberState(String prescriberState) {
        this.prescriberState = prescriberState;
    }
    
   // @Column(name="Prescriber_Zip_Code", length=10)
    public String getPrescriberZipCode() {
        return this.prescriberZipCode;
    }
    
    public void setPrescriberZipCode(String prescriberZipCode) {
        this.prescriberZipCode = prescriberZipCode;
    }
    
   // @Column(name="Tot_Drug_Cost_Paid_To_Pharmacy", nullable=false, precision=11, scale=3)
    public BigDecimal getTotDrugCostPaidToPharmacy() {
        return this.totDrugCostPaidToPharmacy;
    }
    
    public void setTotDrugCostPaidToPharmacy(BigDecimal totDrugCostPaidToPharmacy) {
        this.totDrugCostPaidToPharmacy = totDrugCostPaidToPharmacy;
    }
    
   // @Column(name="Pt_Out_Of_Pocket", precision=11, scale=3)
    public BigDecimal getPtOutOfPocket() {
        return this.ptOutOfPocket;
    }
    
    public void setPtOutOfPocket(BigDecimal ptOutOfPocket) {
        this.ptOutOfPocket = ptOutOfPocket;
    }
    
   // @Column(name="CI_Paper_Claim_Flag")
    public Integer getCiPaperClaimFlag() {
        return this.ciPaperClaimFlag;
    }
    
    public void setCiPaperClaimFlag(Integer ciPaperClaimFlag) {
        this.ciPaperClaimFlag = ciPaperClaimFlag;
    }
    
  //  @Column(name="CI_Other_Processor_Flag")
    public Integer getCiOtherProcessorFlag() {
        return this.ciOtherProcessorFlag;
    }
    
    public void setCiOtherProcessorFlag(Integer ciOtherProcessorFlag) {
        this.ciOtherProcessorFlag = ciOtherProcessorFlag;
    }
    
    //@Column(name="CI_Batch_Processed_Flag")
    public Integer getCiBatchProcessedFlag() {
        return this.ciBatchProcessedFlag;
    }
    
    public void setCiBatchProcessedFlag(Integer ciBatchProcessedFlag) {
        this.ciBatchProcessedFlag = ciBatchProcessedFlag;
    }
    
   // @Column(name="CI_Test_Claim_Flag")
    public Integer getCiTestClaimFlag() {
        return this.ciTestClaimFlag;
    }
    
    public void setCiTestClaimFlag(Integer ciTestClaimFlag) {
        this.ciTestClaimFlag = ciTestClaimFlag;
    }
    
 //   @Column(name="CI_Direct_Reimbursement_Flag")
    public Integer getCiDirectReimbursementFlag() {
        return this.ciDirectReimbursementFlag;
    }
    
    public void setCiDirectReimbursementFlag(Integer ciDirectReimbursementFlag) {
        this.ciDirectReimbursementFlag = ciDirectReimbursementFlag;
    }
    
   // @Column(name="Professional_Service_Fee", precision=22, scale=0)
    public Double getProfessionalServiceFee() {
        return this.professionalServiceFee;
    }
    
    public void setProfessionalServiceFee(Double professionalServiceFee) {
        this.professionalServiceFee = professionalServiceFee;
    }
    
   // @Column(name="Drug_Dosage_Form", length=10)
    public String getDrugDosageForm() {
        return this.drugDosageForm;
    }
    
    public void setDrugDosageForm(String drugDosageForm) {
        this.drugDosageForm = drugDosageForm;
    }
    
  //  @Column(name="Drug_Strength", length=10)
    public String getDrugStrength() {
        return this.drugStrength;
    }
    
    public void setDrugStrength(String drugStrength) {
        this.drugStrength = drugStrength;
    }
    
    //@Column(name="Refills_Allowed")
    public Integer getRefillsAllowed() {
        return this.refillsAllowed;
    }
    
    public void setRefillsAllowed(Integer refillsAllowed) {
        this.refillsAllowed = refillsAllowed;
    }
    
   // @Column(name="Ingredient_Cost_Paid", nullable=false, precision=11, scale=3)
    public BigDecimal getIngredientCostPaid() {
        return this.ingredientCostPaid;
    }
    
    public void setIngredientCostPaid(BigDecimal ingredientCostPaid) {
        this.ingredientCostPaid = ingredientCostPaid;
    }
    
  //  @Column(name="Flat_Sales_Tax_Amount_Paid", nullable=false, precision=22, scale=0)
    public double getFlatSalesTaxAmountPaid() {
        return this.flatSalesTaxAmountPaid;
    }
    
    public void setFlatSalesTaxAmountPaid(double flatSalesTaxAmountPaid) {
        this.flatSalesTaxAmountPaid = flatSalesTaxAmountPaid;
    }
    
   // @Column(name="Usual_Customary_Amount", nullable=false, precision=8)
    public BigDecimal getUsualCustomaryAmount() {
        return this.usualCustomaryAmount;
    }
    
    public void setUsualCustomaryAmount(BigDecimal usualCustomaryAmount) {
        this.usualCustomaryAmount = usualCustomaryAmount;
    }
    
    //@Column(name="Prior_Auth_Code")
    public Long getPriorAuthCode() {
        return this.priorAuthCode;
    }
    
    public void setPriorAuthCode(Long priorAuthCode) {
        this.priorAuthCode = priorAuthCode;
    }
    
  //  @Column(name="Pharmacy_Address_1", length=100)
    public String getPharmacyAddress1() {
        return this.pharmacyAddress1;
    }
    
    public void setPharmacyAddress1(String pharmacyAddress1) {
        this.pharmacyAddress1 = pharmacyAddress1;
    }
    
  //  @Column(name="Pharmacy_Address_2", length=100)
    public String getPharmacyAddress2() {
        return this.pharmacyAddress2;
    }
    
    public void setPharmacyAddress2(String pharmacyAddress2) {
        this.pharmacyAddress2 = pharmacyAddress2;
    }
    
   // @Column(name="Dispense_Fee_Paid", nullable=false, precision=22, scale=0)
    public double getDispenseFeePaid() {
        return this.dispenseFeePaid;
    }
    
    public void setDispenseFeePaid(double dispenseFeePaid) {
        this.dispenseFeePaid = dispenseFeePaid;
    }
    
  //  @Column(name="Prescriber_Specialty", length=40)
    public String getPrescriberSpecialty() {
        return this.prescriberSpecialty;
    }
    
    public void setPrescriberSpecialty(String prescriberSpecialty) {
        this.prescriberSpecialty = prescriberSpecialty;
    }
    
  //  @Column(name="Price_Source", nullable=false, length=20)
    public String getPriceSource() {
        return this.priceSource;
    }
    
    public void setPriceSource(String priceSource) {
        this.priceSource = priceSource;
    }
    
  //  @Column(name="Reversal_Date_TimeStamp", length=50)
    public String getReversalDateTimeStamp() {
        return this.reversalDateTimeStamp;
    }
    
    public void setReversalDateTimeStamp(String reversalDateTimeStamp) {
        this.reversalDateTimeStamp = reversalDateTimeStamp;
    }
//    @Temporal(TemporalType.DATE)
//    @Column(name="Rx_Written_Date", length=10)
    public Date getRxWrittenDate() {
        return this.rxWrittenDate;
    }
    
    public void setRxWrittenDate(Date rxWrittenDate) {
        this.rxWrittenDate = rxWrittenDate;
    }
    
    //@Column(name="Pharmacy_NCPDP")
    public Long getPharmacyNcpdp() {
        return this.pharmacyNcpdp;
    }
    
    public void setPharmacyNcpdp(Long pharmacyNcpdp) {
        this.pharmacyNcpdp = pharmacyNcpdp;
    }
    
   // @Column(name="Submitted_Cardholder_First_Name", length=50)
    public String getSubmittedCardholderFirstName() {
        return this.submittedCardholderFirstName;
    }
    
    public void setSubmittedCardholderFirstName(String submittedCardholderFirstName) {
        this.submittedCardholderFirstName = submittedCardholderFirstName;
    }
    
   // @Column(name="Submitted_Cardholder_Last_Name", length=50)
    public String getSubmittedCardholderLastName() {
        return this.submittedCardholderLastName;
    }
    
    public void setSubmittedCardholderLastName(String submittedCardholderLastName) {
        this.submittedCardholderLastName = submittedCardholderLastName;
    }
//    @Temporal(TemporalType.DATE)
//    @Column(name="Submitted_Cardholder_DOB", length=10)
    public Date getSubmittedCardholderDob() {
        return this.submittedCardholderDob;
    }
    
    public void setSubmittedCardholderDob(Date submittedCardholderDob) {
        this.submittedCardholderDob = submittedCardholderDob;
    }
    
    //@Column(name="Submitted_Cardholder_Gender", length=1)
    public String getSubmittedCardholderGender() {
        return this.submittedCardholderGender;
    }
    
    public void setSubmittedCardholderGender(String submittedCardholderGender) {
        this.submittedCardholderGender = submittedCardholderGender;
    }
    
   // @Column(name="Submitted_Patient_FName", length=12)
    public String getSubmittedPatientFname() {
        return this.submittedPatientFname;
    }
    
    public void setSubmittedPatientFname(String submittedPatientFname) {
        this.submittedPatientFname = submittedPatientFname;
    }
    
    //@Column(name="Submitted_Patient_LName", length=15)
    public String getSubmittedPatientLname() {
        return this.submittedPatientLname;
    }
    
    public void setSubmittedPatientLname(String submittedPatientLname) {
        this.submittedPatientLname = submittedPatientLname;
    }
    
   // @Column(name="File_Name", nullable=false, length=500)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Insertion_Date", length=19)
    public Date getInsertionDate() {
        return this.insertionDate;
    }
    
    public void setInsertionDate(Date insertionDate) {
        this.insertionDate = insertionDate;
    }
    
//    @Column(name="Enrollment_Id")
    public Integer getEnrollmentId() {
        return this.enrollmentId;
    }
    
    public void setEnrollmentId(Integer enrollmentId) {
        this.enrollmentId = enrollmentId;
    }
    
//    @Column(name="Communication_Source_Code", length=4)
    public String getCommunicationSourceCode() {
        return this.communicationSourceCode;
    }
    
    public void setCommunicationSourceCode(String communicationSourceCode) {
        this.communicationSourceCode = communicationSourceCode;
    }
    
//    @Column(name="Communication_Method", length=1)
    public String getCommunicationMethod() {
        return this.communicationMethod;
    }
    
    public void setCommunicationMethod(String communicationMethod) {
        this.communicationMethod = communicationMethod;
    }
    
//    @Column(name="Communication_Id", length=50)
    public String getCommunicationId() {
        return this.communicationId;
    }
    
    public void setCommunicationId(String communicationId) {
        this.communicationId = communicationId;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Enrollment_Date", length=19)
    public Date getEnrollmentDate() {
        return this.enrollmentDate;
    }
    
    public void setEnrollmentDate(Date enrollmentDate) {
        this.enrollmentDate = enrollmentDate;
    }
    
//    @Column(name="isValidPhone", length=3)
    public String getIsValidPhone() {
        return this.isValidPhone;
    }
    
    public void setIsValidPhone(String isValidPhone) {
        this.isValidPhone = isValidPhone;
    }
    
    //@Column(name="Claim_Authorization_Number", length=20)
    public String getClaimAuthorizationNumber() {
        return this.claimAuthorizationNumber;
    }
    
    public void setClaimAuthorizationNumber(String claimAuthorizationNumber) {
        this.claimAuthorizationNumber = claimAuthorizationNumber;
    }
    
  //  @Column(name="Orignal_Claim_Authorization_Number", length=20)
    public String getOrignalClaimAuthorizationNumber() {
        return this.orignalClaimAuthorizationNumber;
    }
    
    public void setOrignalClaimAuthorizationNumber(String orignalClaimAuthorizationNumber) {
        this.orignalClaimAuthorizationNumber = orignalClaimAuthorizationNumber;
    }
    
    //@Column(name="Other_Coverage_Code", length=10)
    public String getOtherCoverageCode() {
        return this.otherCoverageCode;
    }
    
    public void setOtherCoverageCode(String otherCoverageCode) {
        this.otherCoverageCode = otherCoverageCode;
    }
    
   // @Column(name="Other_Payer_Rejection_Code", length=25)
    public String getOtherPayerRejectionCode() {
        return this.otherPayerRejectionCode;
    }
    
    public void setOtherPayerRejectionCode(String otherPayerRejectionCode) {
        this.otherPayerRejectionCode = otherPayerRejectionCode;
    }
    
  //  @Column(name="Other_Payer_Id_Qualifier", length=10)
    public String getOtherPayerIdQualifier() {
        return this.otherPayerIdQualifier;
    }
    
    public void setOtherPayerIdQualifier(String otherPayerIdQualifier) {
        this.otherPayerIdQualifier = otherPayerIdQualifier;
    }
    
  //  @Column(name="Other_Payer_Id", length=20)
    public String getOtherPayerId() {
        return this.otherPayerId;
    }
    
    public void setOtherPayerId(String otherPayerId) {
        this.otherPayerId = otherPayerId;
    }
    
    //@Column(name="Input_Reference_Number")
    public Long getInputReferenceNumber() {
        return this.inputReferenceNumber;
    }
    
    public void setInputReferenceNumber(Long inputReferenceNumber) {
        this.inputReferenceNumber = inputReferenceNumber;
    }
    
  //  @Column(name="Enrollment_Path", length=1)
    public String getEnrollmentPath() {
        return this.enrollmentPath;
    }
    
    public void setEnrollmentPath(String enrollmentPath) {
        this.enrollmentPath = enrollmentPath;
    }
    
   // @Column(name="Redemption_Id")
    public Integer getRedemptionId() {
        return this.redemptionId;
    }
    
    public void setRedemptionId(Integer redemptionId) {
        this.redemptionId = redemptionId;
    }

//     @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Posting_Date_TimeStamp", length=19)
    public Date getPostingDateTimeStamp() {
        return postingDateTimeStamp;
    }

    public void setPostingDateTimeStamp(Date postingDateTimeStamp) {
        this.postingDateTimeStamp = postingDateTimeStamp;
    }




}


