package com.ssa.cms.model;
// Generated May 17, 2013 5:48:00 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailOptInOut generated by hbm2java
 */
@Entity
@Table(name = "EmailOptInOut")
public class EmailOptInOut implements java.io.Serializable {

    private long ecrSeqNo;
    private Integer campaignId;
    private String campaignName;
    private String email;
    private String optInOut;
    private String statusCode;
    private Date effectiveDate;
    private String phoneNo;

    public EmailOptInOut() {
    }

    public EmailOptInOut(long ecrSeqNo, String email, String optInOut, Date effectiveDate) {
        this.ecrSeqNo = ecrSeqNo;
        this.email = email;
        this.optInOut = optInOut;
        this.effectiveDate = effectiveDate;
    }

    public EmailOptInOut(long ecrSeqNo, Integer campaignId, String campaignName, String email, String optInOut, String statusCode, Date effectiveDate) {
        this.ecrSeqNo = ecrSeqNo;
        this.campaignId = campaignId;
        this.campaignName = campaignName;
        this.email = email;
        this.optInOut = optInOut;
        this.statusCode = statusCode;
        this.effectiveDate = effectiveDate;
    }

    @Id

    @Column(name = "ECR_Seq_No", unique = true, nullable = false)
    public long getEcrSeqNo() {
        return this.ecrSeqNo;
    }

    public void setEcrSeqNo(long ecrSeqNo) {
        this.ecrSeqNo = ecrSeqNo;
    }

    @Column(name = "Campaign_Id")
    public Integer getCampaignId() {
        return this.campaignId;
    }

    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    @Column(name = "Campaign_Name")
    public String getCampaignName() {
        return this.campaignName;
    }

    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    @Column(name = "Email", nullable = false, length = 200)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Opt_In_Out", nullable = false, length = 1)
    public String getOptInOut() {
        return this.optInOut;
    }

    public void setOptInOut(String optInOut) {
        this.optInOut = optInOut;
    }

    @Column(name = "Status_Code", length = 2)
    public String getStatusCode() {
        return this.statusCode;
    }

    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Effective_Date", nullable = false, length = 19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    @Column(name = "Phone_Number")
    public String getPhoneNo() {
        return phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
}
