package com.ssa.cms.model;
// Generated May 7, 2013 1:09:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FileProcessingLog generated by hbm2java
 * 
 * FileProcessingLog table not in used
 */
//@Entity
//@Table(name="FileProcessingLog")
public class FileProcessingLog  implements java.io.Serializable {


     private Long sequenceNumber;
     private String transactionNumber;
     private String fileName;
     private String fileTypeCode;
     private String fieldName;
     private String fieldValue;
     private String message;
     private int campaignId;
     private int redemptionId;
     private Date effectiveDate;
     private Date endDate;

    public FileProcessingLog() {
    }

	
    public FileProcessingLog(String fileName, String fileTypeCode, String fieldName, String message, int campaignId, int redemptionId, Date effectiveDate) {
        this.fileName = fileName;
        this.fileTypeCode = fileTypeCode;
        this.fieldName = fieldName;
        this.message = message;
        this.campaignId = campaignId;
        this.redemptionId = redemptionId;
        this.effectiveDate = effectiveDate;
    }
    public FileProcessingLog(String fileName, String fileTypeCode, String fieldName, String message, int campaignId, int redemptionId, Date effectiveDate, Date endDate) {
       this.fileName = fileName;
       this.fileTypeCode = fileTypeCode;
       this.fieldName = fieldName;
       this.message = message;
       this.campaignId = campaignId;
       this.redemptionId = redemptionId;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
    }
   
//     @Id @GeneratedValue(strategy=IDENTITY)
//    
//    @Column(name="Sequence_Number", unique=true, nullable=false)
    public Long getSequenceNumber() {
        return this.sequenceNumber;
    }
    
    public void setSequenceNumber(Long sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }
    
    
    //@Column(name="Transaction_Number", nullable=true, length=50)
    public String getTransactionNumber() {
        return this.transactionNumber;
    }
    
    public void setTransactionNumber(String transactionNumber) {
        this.transactionNumber = transactionNumber;
    }
    
    
    //@Column(name="File_Name", length=200)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
  //  @Column(name="File_Type_Code", nullable=false, length=6)
    public String getFileTypeCode() {
        return this.fileTypeCode;
    }
    
    public void setFileTypeCode(String fileTypeCode) {
        this.fileTypeCode = fileTypeCode;
    }
    
    //@Column(name="Field_Name", nullable=false, length=100)
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    
    //@Column(name="Field_Value", nullable=true, length=500)
    public String getFieldValue() {
        return this.fieldValue;
    }
    
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue;
    }
    
    
            
    
    //@Column(name="Message", nullable=false, length=100)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    
  //  @Column(name="Campaign_Id", nullable=false)
    public int getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(int campaignId) {
        this.campaignId = campaignId;
    }
    
   // @Column(name="Redemption_Id", nullable=false)
    public int getRedemptionId() {
        return this.redemptionId;
    }
    
    public void setRedemptionId(int redemptionId) {
        this.redemptionId = redemptionId;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


