package com.ssa.cms.model;
// Generated May 7, 2013 2:13:48 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GroupHasFolderHasCampaign generated by hbm2java
 */
@Entity
@Table(name = "GroupHasFolderHasCampaign")
public class GroupHasFolderHasCampaign implements java.io.Serializable {

    private GroupHasFolderHasCampaignId id;
    private String sourceType;

    public GroupHasFolderHasCampaign() {
    }

    public GroupHasFolderHasCampaign(GroupHasFolderHasCampaignId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "fhCid", column =
                @Column(name = "FhCId", nullable = false)),
        @AttributeOverride(name = "folderId", column =
                @Column(name = "FolderId", nullable = false)),
        @AttributeOverride(name = "campaignId", column =
                @Column(name = "CampaignId", nullable = false)),
        @AttributeOverride(name = "groupId", column =
                @Column(name = "GroupId", nullable = false)),
        @AttributeOverride(name = "campaignMessagesId", column =
                @Column(name = "CampaignMessagesId", nullable = false)) })
    public GroupHasFolderHasCampaignId getId() {
        return this.id;
    }

    public void setId(GroupHasFolderHasCampaignId id) {
        this.id = id;
    }

    @Column(name = "SourceType")
    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }
}
