package com.ssa.cms.model;
// Generated Apr 29, 2013 2:34:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstantRequest generated by hbm2java
 * 
 * InstantRequest table not in used and not exist in db
 */
//@Entity
//@Table(name="InstantRequest")
public class InstantRequest  implements java.io.Serializable {


     private Long id;
     private Campaigns campaigns;
     private String text;
     private String email;
     private String homePhone;
     private String flagMessage;
     private String memberId;
     private Date timeStamp;
     private String groupNumber1;
     private String groupNumber2;
     private String groupNumber3;
     private String groupNumber4;
     private String groupNumber5;
     private Date effectiveDate;
     private Date endDate;
     private Long sessionId;
     private String isValidPhone;
     private String insertedBy;

    public InstantRequest() {
    }

	
    public InstantRequest(Campaigns campaigns, Date effectiveDate, String isValidPhone) {
        this.campaigns = campaigns;
        this.effectiveDate = effectiveDate;
        this.isValidPhone = isValidPhone;
    }
    public InstantRequest(Campaigns campaigns, String text, String email, String homePhone, String flagMessage, String memberId, Date timeStamp, String groupNumber1, String groupNumber2, String groupNumber3, String groupNumber4, String groupNumber5, Date effectiveDate, Date endDate, Long sessionId, String isValidPhone, String insertedBy) {
       this.campaigns = campaigns;
       this.text = text;
       this.email = email;
       this.homePhone = homePhone;
       this.flagMessage = flagMessage;
       this.memberId = memberId;
       this.timeStamp = timeStamp;
       this.groupNumber1 = groupNumber1;
       this.groupNumber2 = groupNumber2;
       this.groupNumber3 = groupNumber3;
       this.groupNumber4 = groupNumber4;
       this.groupNumber5 = groupNumber5;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
       this.sessionId = sessionId;
       this.isValidPhone = isValidPhone;
       this.insertedBy = insertedBy;
    }
   
//     @Id @GeneratedValue(strategy=IDENTITY)
//    
//    @Column(name="Id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
//@ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="CampaignId", nullable=false)
    public Campaigns getCampaigns() {
        return this.campaigns;
    }
    
    public void setCampaigns(Campaigns campaigns) {
        this.campaigns = campaigns;
    }
    
//    @Column(name="Text", length=20)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
//    @Column(name="Email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
//    @Column(name="Home_Phone", length=11)
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    
//    @Column(name="Flag_Message", length=5)
    public String getFlagMessage() {
        return this.flagMessage;
    }
    
    public void setFlagMessage(String flagMessage) {
        this.flagMessage = flagMessage;
    }
    
//    @Column(name="Member_Id", length=20)
    public String getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Time_Stamp", length=19)
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }
    
//    @Column(name="Group_Number_1", length=10)
    public String getGroupNumber1() {
        return this.groupNumber1;
    }
    
    public void setGroupNumber1(String groupNumber1) {
        this.groupNumber1 = groupNumber1;
    }
    
//    @Column(name="Group_Number_2", length=10)
    public String getGroupNumber2() {
        return this.groupNumber2;
    }
    
    public void setGroupNumber2(String groupNumber2) {
        this.groupNumber2 = groupNumber2;
    }
    
//    @Column(name="Group_Number_3", length=10)
    public String getGroupNumber3() {
        return this.groupNumber3;
    }
    
    public void setGroupNumber3(String groupNumber3) {
        this.groupNumber3 = groupNumber3;
    }
    
//    @Column(name="Group_Number_4", length=10)
    public String getGroupNumber4() {
        return this.groupNumber4;
    }
    
    public void setGroupNumber4(String groupNumber4) {
        this.groupNumber4 = groupNumber4;
    }
    
//    @Column(name="Group_Number_5", length=10)
    public String getGroupNumber5() {
        return this.groupNumber5;
    }
    
    public void setGroupNumber5(String groupNumber5) {
        this.groupNumber5 = groupNumber5;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
//    @Column(name="Session_Id")
    public Long getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }
    
//    @Column(name="isValidPhone", nullable=false, length=3)
    public String getIsValidPhone() {
        return this.isValidPhone;
    }
    
    public void setIsValidPhone(String isValidPhone) {
        this.isValidPhone = isValidPhone;
    }
    
//    @Column(name="Inserted_By", length=20)
    public String getInsertedBy() {
        return this.insertedBy;
    }
    
    public void setInsertedBy(String insertedBy) {
        this.insertedBy = insertedBy;
    }




}


