package com.ssa.cms.model;
// Generated Jul 8, 2013 5:57:49 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IvroutboundQueue generated by hbm2java
 */
@Entity
@Table(name = "IVROutboundQueue")
public class IvroutboundQueue implements java.io.Serializable {

    private Long id;
    private String phoneNumber;
    private String servoId;
    private String requestUrl;
    private Long inputReferenceNumber;
    private String isMobile;
    private String isLandLine;
    private Date effectiveDate;
    private Date endDate;
    private String callDailed;
    private Long outBoundRequestId;
    private int sessionId;
    private int folderId;
    private int campaignId;
    private int messageTypeId;
    private Integer intervalId;
    private String intervalDescription;
    private String eventDetail;
    private int redemptionId;
    private String messageContext; 

    public IvroutboundQueue() {
    }

    public IvroutboundQueue(Date effectiveDate, int sessionId) {

        this.effectiveDate = effectiveDate;
        this.sessionId = sessionId;
    }

    public IvroutboundQueue(String phoneNumber,String messageContext, String servoId, String requestUrl, int messageTypeId, Long inputReferenceNumber, String isMobile, String isLandLine, Date effectiveDate, Date endDate, String callDailed, Long outBoundRequestId, int sessionId, int folderId, int campaignId, Integer intervalId,String intervalDescription,String eventDetail,Integer redemptionId) {
        this.phoneNumber = phoneNumber;
        this.servoId = servoId;
        this.requestUrl = requestUrl;
        this.messageTypeId = messageTypeId;

        this.inputReferenceNumber = inputReferenceNumber;
        this.isMobile = isMobile;
        this.isLandLine = isLandLine;
        this.effectiveDate = effectiveDate;
        this.endDate = endDate;
        this.callDailed = callDailed;
        this.outBoundRequestId = outBoundRequestId;
        this.sessionId = sessionId;
        this.eventDetail=eventDetail;
        this.intervalId=intervalId;
        this.intervalDescription=intervalDescription;
        this.redemptionId=redemptionId;
        this.messageContext = messageContext;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "Phone_Number", length = 100)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "Servo_Id")
    public String getServoId() {
        return this.servoId;
    }

    public void setServoId(String servoId) {
        this.servoId = servoId;
    }

    @Column(name = "Request_URL", length = 200)
    public String getRequestUrl() {
        return this.requestUrl;
    }

    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    @Column(name = "Input_Reference_Number")
    public Long getInputReferenceNumber() {
        return this.inputReferenceNumber;
    }

    public void setInputReferenceNumber(Long inputReferenceNumber) {
        this.inputReferenceNumber = inputReferenceNumber;
    }

    @Column(name = "Is_Mobile", length = 3)
    public String getIsMobile() {
        return this.isMobile;
    }

    public void setIsMobile(String isMobile) {
        this.isMobile = isMobile;
    }

    @Column(name = "Is_Land_Line", length = 3)
    public String getIsLandLine() {
        return this.isLandLine;
    }

    public void setIsLandLine(String isLandLine) {
        this.isLandLine = isLandLine;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Effective_Date", nullable = false, length = 19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "End_Date", length = 19)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Column(name = "Call_Dailed", length = 4)
    public String getCallDailed() {
        return this.callDailed;
    }

    public void setCallDailed(String callDailed) {
        this.callDailed = callDailed;
    }

    @Column(name = "Out_Bound_Request_Id")
    public Long getOutBoundRequestId() {
        return this.outBoundRequestId;
    }

    public void setOutBoundRequestId(Long outBoundRequestId) {
        this.outBoundRequestId = outBoundRequestId;
    }
    @Column(name="Redemption_Id", nullable=false)
    public int getRedemptionId() {
        return this.redemptionId;
    }
    
    public void setRedemptionId(int redemptionId) {
        this.redemptionId = redemptionId;
    }
    
    @Column(name = "Session_Id", nullable = false)
    public int getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

    @Column(name = "FolderId", nullable = false)
    public int getFolderId() {
        return this.folderId;
    }

    public void setFolderId(int folderId) {
        this.folderId = folderId;
    }

    @Column(name = "Campaign_Id", nullable = false)
    public int getCampaignId() {
        return this.campaignId;
    }

    public void setCampaignId(int campaignId) {
        this.campaignId = campaignId;
    }

    @Column(name = "MessageTypeId", nullable = false)
    public int getMessageTypeId() {
        return this.messageTypeId;
    }

    public void setMessageTypeId(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
     @Column(name="Interval_Id")
    public Integer getIntervalId() {
        return this.intervalId;
    }
    
    public void setIntervalId(Integer intervalId) {
        this.intervalId = intervalId;
    }
    
    @Column(name="Interval_Description", length=50)
    public String getIntervalDescription() {
        return this.intervalDescription;
    }
    
    public void setIntervalDescription(String intervalDescription) {
        this.intervalDescription = intervalDescription;
    }
    
    @Column(name="Event_Detail", length=50)
    public String getEventDetail() {
        return this.eventDetail;
    }
    
    public void setEventDetail(String eventDetail) {
        this.eventDetail = eventDetail;
    }
 
      @Column(name="Message_Context", length=40)
    public String getMessageContext() {
        return this.messageContext;
    }
    
    public void setMessageContext(String messageContext) {
        this.messageContext = messageContext;
    }
}
