package com.ssa.cms.model;
// Generated May 6, 2013 7:07:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Raryesreceived generated by hbm2java
 * 
 * RARYESReceived table not in used
 */
//@Entity
//@Table(name="RARYESReceived")
public class Raryesreceived  implements java.io.Serializable {


     private Long id;
     private String communicationId;
     private String communicationMethod;
     private Integer campaignId;
     private Integer folderId;
     private Integer shortCode;
     private Integer messageTypeId;
     private Integer redemptionId;
     private String messageResponse;
     private Date effectiveDate;
     private Date endDate;
     private String communicationPath;

    public Raryesreceived() {
    }

	
    public Raryesreceived(String communicationId, String communicationMethod, Date effectiveDate) {
        this.communicationId = communicationId;
        this.communicationMethod = communicationMethod;
        this.effectiveDate = effectiveDate;
    }
    public Raryesreceived(String communicationId, String communicationMethod, Integer campaignId, Integer folderId, Integer shortCode, Integer messageTypeId, Integer redemptionId, String messageResponse, Date effectiveDate, Date endDate) {
       this.communicationId = communicationId;
       this.communicationMethod = communicationMethod;
       this.campaignId = campaignId;
       this.folderId = folderId;
       this.shortCode = shortCode;
       this.messageTypeId = messageTypeId;
       this.redemptionId = redemptionId;
       this.messageResponse = messageResponse;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
    }
   
//     @Id @GeneratedValue(strategy=IDENTITY)
//    
//    @Column(name="Id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
   // @Column(name="Communication_Id", nullable=false, length=200)
    public String getCommunicationId() {
        return this.communicationId;
    }
    
    public void setCommunicationId(String communicationId) {
        this.communicationId = communicationId;
    }
    
   // @Column(name="Communication_Method", nullable=false, length=1)
    public String getCommunicationMethod() {
        return this.communicationMethod;
    }
    
    public void setCommunicationMethod(String communicationMethod) {
        this.communicationMethod = communicationMethod;
    }
    
   // @Column(name="Campaign_Id")
    public Integer getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }
    
   // @Column(name="Folder_Id")
    public Integer getFolderId() {
        return this.folderId;
    }
    
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }
    
  //  @Column(name="Short_Code")
    public Integer getShortCode() {
        return this.shortCode;
    }
    
    public void setShortCode(Integer shortCode) {
        this.shortCode = shortCode;
    }
    
  //  @Column(name="Message_Type_Id")
    public Integer getMessageTypeId() {
        return this.messageTypeId;
    }
    
    public void setMessageTypeId(Integer messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
    
   // @Column(name="Redemption_Id")
    public Integer getRedemptionId() {
        return this.redemptionId;
    }
    
    public void setRedemptionId(Integer redemptionId) {
        this.redemptionId = redemptionId;
    }
    
   // @Column(name="Message_Response", length=20)
    public String getMessageResponse() {
        return this.messageResponse;
    }
    
    public void setMessageResponse(String messageResponse) {
        this.messageResponse = messageResponse;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    //@Column(name="Communication_Path", length=10)
    public String getCommunicationPath() {
        return communicationPath;
    }

    public void setCommunicationPath(String communicationPath) {
        this.communicationPath = communicationPath;
    }




}


