package com.ssa.cms.model;
// Generated May 14, 2013 12:15:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Url generated by hbm2java
 */
@Entity
@Table(name="URL")
public class Url  implements java.io.Serializable {


     private String code;
     private String narrative;
     private String url;
     private Date effectiveDate;
     private Date endDate;

    public Url() {
    }

	
    public Url(String code, String narrative, String url, Date effectiveDate) {
        this.code = code;
        this.narrative = narrative;
        this.url = url;
        this.effectiveDate = effectiveDate;
    }
    public Url(String code, String narrative, String url, Date effectiveDate, Date endDate) {
       this.code = code;
       this.narrative = narrative;
       this.url = url;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
    }
   
     @Id 
    
    @Column(name="Code", unique=true, nullable=false, length=15)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="Narrative", nullable=false, length=50)
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }
    
    @Column(name="URL", nullable=false, length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


