package com.ssa.cms.model;
// Generated Dec 25, 2013 4:50:28 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserBrand generated by hbm2java
 */
@Entity
@Table(name="UserBrand")
public class UserBrand  implements java.io.Serializable {


     private Integer userBrandId;
     private int userId;
     private int brandId;
     private String campaignIds;

    public UserBrand() {
    }

	
    public UserBrand(int userId, int brandId) {
        this.userId = userId;
        this.brandId = brandId;
    }
    public UserBrand(int userId, int brandId, String campaignIds) {
       this.userId = userId;
       this.brandId = brandId;
       this.campaignIds = campaignIds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="UserBrandId", unique=true, nullable=false)
    public Integer getUserBrandId() {
        return this.userBrandId;
    }
    
    public void setUserBrandId(Integer userBrandId) {
        this.userBrandId = userBrandId;
    }
    
    @Column(name="UserId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="BrandId", nullable=false)
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }
    
    @Column(name="CampaignIds", length=100)
    public String getCampaignIds() {
        return this.campaignIds;
    }
    
    public void setCampaignIds(String campaignIds) {
        this.campaignIds = campaignIds;
    }




}


