package com.ssa.cms.model;
// Generated Jul 9, 2013 12:00:56 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IvrvendorInfo generated by hbm2java
 */
@Entity
@Table(name="IVRVendorInfo")
public class IvrvendorInfo  implements java.io.Serializable {


     private Integer seqNo;
     private String url;
     private String vendorName;
     private Date effectiveDate;
     private Date endDate;

    public IvrvendorInfo() {
    }

	
    public IvrvendorInfo(String url, Date effectiveDate) {
        this.url = url;
        this.effectiveDate = effectiveDate;
    }
    public IvrvendorInfo(String url, String vendorName, Date effectiveDate, Date endDate) {
       this.url = url;
       this.vendorName = vendorName;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Seq_No", unique=true, nullable=false)
    public Integer getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }
    
    @Column(name="URL", nullable=false, length=250)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="Vendor_Name", length=50)
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


