package com.ssa.cms.model;
// Generated Jul 8, 2013 5:57:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IvrrequestResponse generated by hbm2java
 */
@Entity
@Table(name="IVRRequestResponse")
public class IvrrequestResponse  implements java.io.Serializable {


     private Integer ivrReqNo;
     private int campaignId;
     private String servoId;
     private String messageContext;
     private Date cardholderDob;
     private Integer claimStatus;
     private String fileName;
     private String fileTypeCode;
     private Date fillDate;
     private int folderId;
     private String requestUrl;
     private String responseXml;
     private String errorCode;
     private String errorDescription;
     private int messageTypeId;
     private String ndcNumber;
     private String phoneNumber;
     private int redemptionId;
     private String rxGroupNumber;
     private Date effectiveDate;
     private Date endDate;
     private Long inputReferenceNo;
     private Integer intervalId;
     private String intervalDescription;
     private String eventDetail;
     private Boolean isMobile;
     private Boolean isLandLine;
     private String parameterList;

    public IvrrequestResponse() {
    }

	
    public IvrrequestResponse(int campaignId, Date cardholderDob, String fileTypeCode, Date fillDate, int folderId, int messageTypeId, String ndcNumber, String phoneNumber, int redemptionId, String rxGroupNumber, Date effectiveDate, String parameterList) {
        this.campaignId = campaignId;
        this.cardholderDob = cardholderDob;
        this.fileTypeCode = fileTypeCode;
        this.fillDate = fillDate;
        this.folderId = folderId;
        this.messageTypeId = messageTypeId;
        this.ndcNumber = ndcNumber;
        this.phoneNumber = phoneNumber;
        this.redemptionId = redemptionId;
        this.rxGroupNumber = rxGroupNumber;
        this.effectiveDate = effectiveDate;
        this.parameterList = parameterList;
    }
    public IvrrequestResponse(int campaignId, String servoId, String messageContext, Date cardholderDob, Integer claimStatus, String fileName, String fileTypeCode, Date fillDate, int folderId, String requestUrl, String responseXml, String errorCode, String errorDescription, int messageTypeId, String ndcNumber, String phoneNumber, int redemptionId, String rxGroupNumber, Date effectiveDate, Date endDate, Long inputReferenceNo, Integer intervalId, String intervalDescription, String eventDetail, Boolean isMobile, Boolean isLandLine, String parameterList) {
       this.campaignId = campaignId;
       this.servoId = servoId;
       this.messageContext = messageContext;
       this.cardholderDob = cardholderDob;
       this.claimStatus = claimStatus;
       this.fileName = fileName;
       this.fileTypeCode = fileTypeCode;
       this.fillDate = fillDate;
       this.folderId = folderId;
       this.requestUrl = requestUrl;
       this.responseXml = responseXml;
       this.errorCode = errorCode;
       this.errorDescription = errorDescription;
       this.messageTypeId = messageTypeId;
       this.ndcNumber = ndcNumber;
       this.phoneNumber = phoneNumber;
       this.redemptionId = redemptionId;
       this.rxGroupNumber = rxGroupNumber;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
       this.inputReferenceNo = inputReferenceNo;
       this.intervalId = intervalId;
       this.intervalDescription = intervalDescription;
       this.eventDetail = eventDetail;
       this.isMobile = isMobile;
       this.isLandLine = isLandLine;
       this.parameterList = parameterList;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IVR_Req_No", unique=true, nullable=false)
    public Integer getIvrReqNo() {
        return this.ivrReqNo;
    }
    
    public void setIvrReqNo(Integer ivrReqNo) {
        this.ivrReqNo = ivrReqNo;
    }
    
    @Column(name="Campaign_Id", nullable=false)
    public int getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(int campaignId) {
        this.campaignId = campaignId;
    }
    
    @Column(name="Servo_Id", length=20)
    public String getServoId() {
        return this.servoId;
    }
    
    public void setServoId(String servoId) {
        this.servoId = servoId;
    }
    
    @Column(name="Message_Context", length=40)
    public String getMessageContext() {
        return this.messageContext;
    }
    
    public void setMessageContext(String messageContext) {
        this.messageContext = messageContext;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Cardholder_DOB", nullable=false, length=10)
    public Date getCardholderDob() {
        return this.cardholderDob;
    }
    
    public void setCardholderDob(Date cardholderDob) {
        this.cardholderDob = cardholderDob;
    }
    
    @Column(name="Claim_Status")
    public Integer getClaimStatus() {
        return this.claimStatus;
    }
    
    public void setClaimStatus(Integer claimStatus) {
        this.claimStatus = claimStatus;
    }
    
    @Column(name="File_Name", length=125)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="File_Type_Code", nullable=false, length=6)
    public String getFileTypeCode() {
        return this.fileTypeCode;
    }
    
    public void setFileTypeCode(String fileTypeCode) {
        this.fileTypeCode = fileTypeCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Fill_Date", nullable=false, length=10)
    public Date getFillDate() {
        return this.fillDate;
    }
    
    public void setFillDate(Date fillDate) {
        this.fillDate = fillDate;
    }
    
    @Column(name="FolderId", nullable=false)
    public int getFolderId() {
        return this.folderId;
    }
    
    public void setFolderId(int folderId) {
        this.folderId = folderId;
    }
    
    @Column(name="Request_URL", length=200)
    public String getRequestUrl() {
        return this.requestUrl;
    }
    
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }
    
    @Column(name="Response_Xml", length=2000)
    public String getResponseXml() {
        return this.responseXml;
    }
    
    public void setResponseXml(String responseXml) {
        this.responseXml = responseXml;
    }
    
    @Column(name="Error_Code", length=2)
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
    
    @Column(name="Error_Description", length=500)
    public String getErrorDescription() {
        return this.errorDescription;
    }
    
    public void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }
    
    @Column(name="MessageTypeId", nullable=false)
    public int getMessageTypeId() {
        return this.messageTypeId;
    }
    
    public void setMessageTypeId(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
    
    @Column(name="NDC_Number", nullable=false, length=12)
    public String getNdcNumber() {
        return this.ndcNumber;
    }
    
    public void setNdcNumber(String ndcNumber) {
        this.ndcNumber = ndcNumber;
    }
    
    @Column(name="Phone_Number", nullable=false, length=11)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    @Column(name="Redemption_Id", nullable=false)
    public int getRedemptionId() {
        return this.redemptionId;
    }
    
    public void setRedemptionId(int redemptionId) {
        this.redemptionId = redemptionId;
    }
    
    @Column(name="Rx_Group_Number", nullable=false, length=10)
    public String getRxGroupNumber() {
        return this.rxGroupNumber;
    }
    
    public void setRxGroupNumber(String rxGroupNumber) {
        this.rxGroupNumber = rxGroupNumber;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Effective_Date", nullable=false, length=19)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="End_Date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="Input_Reference_No")
    public Long getInputReferenceNo() {
        return this.inputReferenceNo;
    }
    
    public void setInputReferenceNo(Long inputReferenceNo) {
        this.inputReferenceNo = inputReferenceNo;
    }
    
    @Column(name="Interval_Id")
    public Integer getIntervalId() {
        return this.intervalId;
    }
    
    public void setIntervalId(Integer intervalId) {
        this.intervalId = intervalId;
    }
    
    @Column(name="Interval_Description", length=50)
    public String getIntervalDescription() {
        return this.intervalDescription;
    }
    
    public void setIntervalDescription(String intervalDescription) {
        this.intervalDescription = intervalDescription;
    }
    
    @Column(name="Event_Detail", length=50)
    public String getEventDetail() {
        return this.eventDetail;
    }
    
    public void setEventDetail(String eventDetail) {
        this.eventDetail = eventDetail;
    }
    
    @Column(name="Is_Mobile")
    public Boolean getIsMobile() {
        return this.isMobile;
    }
    
    public void setIsMobile(Boolean isMobile) {
        this.isMobile = isMobile;
    }
    
    @Column(name="Is_Land_Line")
    public Boolean getIsLandLine() {
        return this.isLandLine;
    }
    
    public void setIsLandLine(Boolean isLandLine) {
        this.isLandLine = isLandLine;
    }

    @Column(name="ParameterList")
    public String getParameterList() {
        return parameterList;
    }

    public void setParameterList(String parameterList) {
        this.parameterList = parameterList;
    }
}


