package com.ssa.cms.model;
// Generated May 7, 2013 3:38:35 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DailyRedemptionId generated by hbm2java
 */
//@Embeddable
public class DailyRedemptionId  implements java.io.Serializable {


     private String transactionNumber;
     private int claimStatus;

    public DailyRedemptionId() {
    }

    public DailyRedemptionId(String transactionNumber, int claimStatus) {
       this.transactionNumber = transactionNumber;
       this.claimStatus = claimStatus;
    }
   

//    @Column(name="Transaction_Number", nullable=false, length=20)
    public String getTransactionNumber() {
        return this.transactionNumber;
    }
    
    public void setTransactionNumber(String transactionNumber) {
        this.transactionNumber = transactionNumber;
    }

//    @Column(name="Claim_Status", nullable=false)
    public int getClaimStatus() {
        return this.claimStatus;
    }
    
    public void setClaimStatus(int claimStatus) {
        this.claimStatus = claimStatus;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DailyRedemptionId) ) return false;
		 DailyRedemptionId castOther = ( DailyRedemptionId ) other; 
         
		 return ( (this.getTransactionNumber()==castOther.getTransactionNumber()) || ( this.getTransactionNumber()!=null && castOther.getTransactionNumber()!=null && this.getTransactionNumber().equals(castOther.getTransactionNumber()) ) )
 && (this.getClaimStatus()==castOther.getClaimStatus());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransactionNumber() == null ? 0 : this.getTransactionNumber().hashCode() );
         result = 37 * result + this.getClaimStatus();
         return result;
   }   


}


